services:
  app:
    image: fblongobucco/personal-finance-app:latest
    pull_policy: always
    environment:
      SPRING_PROFILES_ACTIVE: postgres
      APP_DB_URL: ${APP_DB_URL:?defina APP_DB_URL no .env}
      APP_DB_USERNAME: ${APP_DB_USERNAME:?defina APP_DB_USERNAME no .env}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD:?defina APP_DB_PASSWORD no .env}
      APP_JWT_SECRET: ${APP_JWT_SECRET:?defina APP_JWT_SECRET no .env}
      APP_ADMIN_EMAIL: ${APP_ADMIN_EMAIL:-admin@personalfinance.local}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD:-admin123}
      BPL_JVM_THREAD_COUNT: "50"
    ports:
      - "8080:8080"
    restart: unless-stopped
